nginx:
  name: wp-proxy
  labels:
    id: c0909942
    app: wp-proxy-app
    env: dev
  image:
    repository: gcr.io/revision-442203/myimage
    tag: "latest"
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80